### ISSUE TITLE
Ubuntu 16.04 LTS fails to install.

### ISSUE THREAD

**Issue by psibernetic** [scarygliders/X11RDP-o-Matic#60]
```
----------------------------------------------------------------------
Preparation complete. Building and packaging xrdp...
----------------------------------------------------------------------
dpkg-buildpackage: warning: using a gain-root-command while being root
tail: cannot open 'debian/changelog' for reading: No such file or directory
dpkg-buildpackage: error: tail of debian/changelog gave error exit status 1
mv: cannot stat 'xrdp*.deb': No such file or directory
./X11rdp-o-matic.sh: line 993: /etc/init.d/xrdp: No such file or directory
dpkg: error processing archive /home/ovan/X11RDP-o-Matic/packages/Xorg/*.deb (--install):
```

**Comment by schuschu** [comment]
Installed on Ubuntu 16.04 LTS. You have to run the dh_make manually because it fails with ioctl on device or something. I added a pause in the script before it is run but I think you can just go into xrdp-0.9.0+master and run dh_make --native --single there. As the script tries to move xrdp it tries the second time you run it anyway but the files created by dh_make exist so the script continues. You still have to delete the systemd files or it won't start the daemon (or just fix it properly). The warning did not cause me any problems.

**Comment by ICANSEEYOU7687** [comment]
I get the same error on 16.04LTS.

I changed into the folder:
xrdp-0.9.0+master

And ran:
dh_make --native --single
Which returned:
Done. Please edit the files in the debian/ subdirectory now.

I am a little confused on what needs to happen next, are you saying that:
./X11rdp-o-matic.sh --justdoit 
Needs to be ran again?

And where are the systemd files that need to be removed?  Sorry for all of the questions!

**Comment by metalefty** [comment]
16.04 is not supported yet. I'll work on it.

**Comment by nerdknight** [comment]
I made a patch adding compatibility with ubuntu 16.04: https://github.com/nerdknight/X11RDP-o-Matic/commit/ecf9b6d6b7385c48011595dedb08f4088a6a8a42

**Comment by metalefty** [comment]
I started to work on this issue in my branch based on your work.

https://github.com/metalefty/X11RDP-o-Matic/tree/ubuntu-16.04

**Comment by metalefty** [comment]
Done. I'll test it works properly on older Ubuntu and merge.

**Comment by metalefty** [comment]
Fixed and merged #61.

**Comment by ghomem** [comment]
Ran x11rdp-o-matic today with 

`./X11rdp-o-matic.sh --noinstall`

and it generated:

> 
> work/packages/x11rdp/x11rdp_0.9.0+master-1_amd64.deb 
> work/packages/xrdp/xrdp_0.9.0+master-1_amd64.deb 

which I installed on my system.

The xrdp service refused to start because the environment file directive on

```
/lib/systemd/system/xrdp.service
/lib/systemd/system/xrdp-sesman.service
```
was /etc/sysconfig/xrdp which does NOT exist on Debian derivatives. Changed it to /etc/defaults/xrdp and the services start.

xrdp is bound to port 3389 but rejects rdesktop connections. I can see in the log

> Oct 12 20:49:40 xenial XRDP[24494]: (24494)(140433281619712)[CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
> Oct 12 20:49:40 xenial XRDP[24494]: (24494)(140433281619712)[CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
> Oct 12 20:49:40 xenial XRDP[24494]: (24494)(140433281619712)[CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)

It seems that the first run is not generating the certificates correctly.

**Comment by ghomem** [comment]
After running manually:

`xrdp-keygen xrdp auto 
systemctl restart xrdp.service`

rdesktop gets to the login window.
